# Generated by Django 4.2.4 on 2023-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='subdomain',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
